from enum import Enum


class CardType(str, Enum):
    ISIC = "ISIC"
    ISIC_SCHOLAR = "ISIC_SCHOLAR"
    ITIC = "ITIC"
    IYTC = "IYTC"
    ALIVE = "ALIVE"


class VerificationMode(str, Enum):
    NUMBER = "NUMBER"
    CARDHOLDER = "CARDHOLDER"
    CHIP = "CHIP"
    PHONE = "PHONE"


class VerificationResult(str, Enum):
    SUCCESSFUL = "SUCCESSFUL"
    FAILED = "FAILED"


class FailureReason(str, Enum):
    INVALID_NUMBER = "INVALID_NUMBER"
    CHECK_LETTER_MISMATCH = "CHECK_LETTER_MISMATCH"
    INVALID_CHIP_NUMBER = "INVALID_CHIP_NUMBER"
    CARD_NOT_FOUND = "CARD_NOT_FOUND"
    CARD_CANCELLED = "CARD_CANCELLED"
    CARD_EXPIRED = "CARD_EXPIRED"
    CARD_VALID_IN_FUTURE = "CARD_VALID_IN_FUTURE"
    NAME_MISMATCH = "NAME_MISMATCH"
    DATE_OF_BIRTH_MISMATCH = "DATE_OF_BIRTH_MISMATCH"
    CARD_VALIDITY_ENDS_EARLIER = "CARD_VALIDITY_ENDS_EARLIER"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"
    OTHER = "OTHER"


class TransactionStatus(str, Enum):
    ISSUED = "ISSUED"
    REVOKED = "REVOKED"